name: verify

on:
  pull_request:
  push:
    branches: [main]

jobs:
  bazel:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - run: bazel test //...
